### ISSUE TITLE
Is there any script planned to be published?

### ISSUE THREAD

**Issue by mt3o** [hpe-idol/idol-enterprise-init#1]
I have to work with IDOL in corpo version. Stumbled upon this repo and feel little disappointed. I know that IDOL has goo enough documentation, but having some files opensourced (as it was planned I guess) would be nice. 
Best regards!

**Comment by brian-beckett-hpe** [comment]
Hiya,

Sorry, I forgot this repo existed... I did have a plan to open source our IDOL startup scripts, but then we decided to start shipping them with IDOL itself.  If you check in the IDOL zip packages, there's an "init" directory that includes startup scripts for multiple different init systems.  They're much better than the ones I was going to put here :)

I'll delete this repo so I don't cause any more confusion.

Sorry about that!

Brian
